# Generated by Django 4.2.11 on 2025-03-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_menucategory_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
